/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author USER
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtRegUsername = new javax.swing.JTextField();
        txtRegPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRegNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRegKonfirmasi = new javax.swing.JPasswordField();
        txtRegEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRegUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 93, 374, -1));
        jPanel1.add(txtRegPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 132, 374, -1));

        jLabel1.setText("Username                  :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 96, -1, -1));

        jLabel2.setText("Password                   :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 132, -1, -1));

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 220, 100, -1));

        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 220, 105, -1));

        jLabel3.setText("Email                        :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 54, -1, -1));

        txtRegNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 16, 374, -1));

        jLabel4.setText("Nama                        :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        jLabel5.setText("Konfirmasi Password   :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 170, -1, -1));
        jPanel1.add(txtRegKonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 167, 374, -1));

        txtRegEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 51, 374, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String username = txtRegUsername.getText();
        String password = new String(txtRegPassword.getPassword()); // Menggunakan getPassword() untuk JPasswordField
        this.dispose();
        new LoginForm().setVisible(true);
        // Validasi input tidak boleh kosong
        if (username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username dan Password wajib diisi!", "Validasi Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        } else if (username.equals("admin") && password.equals("admin123")) {
            // Jika login sukses (sesuai data yang kita masukkan di SQL awal)
            javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil!");
            this.dispose(); // Tutup form login

            // Membuka Main Form (Menu Utama)
            new MainForm().setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Username atau Password salah!", "Login Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
    String nama = txtRegNama.getText();
    String email = txtRegEmail.getText();
    String username = txtRegUsername.getText();
    String password = new String(txtRegPassword.getPassword());
    String konfirmasi = new String(txtRegKonfirmasi.getPassword());

    // 1. Validasi Kolom Kosong
    if (nama.isEmpty() || email.isEmpty() || username.isEmpty() || password.isEmpty() || konfirmasi.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom wajib diisi!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Validasi Format Email Sederhana (Harus mengandung '@')
    if (!email.contains("@") || !email.contains(".")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Format penulisan Email tidak valid!", "Validasi Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Validasi Kecocokan Password & Konfirmasi
    if (!password.equals(konfirmasi)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Password dan Konfirmasi Password tidak cocok!", "Validasi Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Proses Simpan ke Database
    try {
        java.sql.Connection conn = config.Koneksi.getKoneksi();
        String sql = "INSERT INTO tbl_user (username, nama_lengkap, email, password) VALUES (?, ?, ?, ?)";
        try (java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, username);
            ps.setString(2, nama);
            ps.setString(3, email);
            ps.setString(4, password);
            ps.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Akun berhasil terdaftar! Silakan login.");
            this.dispose();
            new LoginForm().setVisible(true);
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Username sudah terdaftar! Gunakan username lain.");
    }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void txtRegUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegUsernameActionPerformed

    private void txtRegNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNamaActionPerformed

    private void txtRegEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRegEmail;
    private javax.swing.JPasswordField txtRegKonfirmasi;
    private javax.swing.JTextField txtRegNama;
    private javax.swing.JPasswordField txtRegPassword;
    private javax.swing.JTextField txtRegUsername;
    // End of variables declaration//GEN-END:variables
}
